spring:
  application:
    name: proxy
server:
  port: 8080
  contextPath: /api-caed

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


